# This shows how GOSCOW service is routed

# port of the server
port : 8000
# from where to serve the static files
static : _/static-files
# script reloading - automatic
reload : true
# describing end points input -> output 
description: _/scripts/routes.raml
# routes information
routes:
  get:
    /hello : json@_/scripts/js/hello.js
    /param/:id  : json@_/scripts/js/param.js

  post:
    /hello : _/scripts/js/hello.js

# db connections
dbs:
  neo4j :
