# This shows how GOSCOW service is routed

# port of the server
port : 8000
# from where to serve the static files
static : _/static-files
# routes information
routes:
  get:
    /hello : _/scripts/js/hello.js
    /param/:id  : _/scripts/js/param.js

  post:
    /hello : _/scripts/js/hello.js
